app = "WolfyBot"  # Sostituisci con il nome desiderato per la tua app Fly.io
primary_region = "fra"    # Scegli una regione geograficamente vicina a te

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "/app/start_bot.sh"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  protocol = "tcp"
  internal_port = 8080
  ports = [ { port = 80, handlers = ["http"] }, { port = 443, handlers = ["tls", "http"] } ]
